# -*- coding: utf-8 -*-
"""Caso3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gWrUEk2gvphCmKpmBq_LZKDQSUEmh6vA

Caso #3 
Estudiantes André Montoya y Gary Carballo 
Administración de datos
"""

from google.colab import drive 
drive.mount('/content/drive/')

#Librerias necesarias#
import pandas as pd
import numpy as np
import statistics

#1-Importar el archivo#
data = pd.read_excel('/content/drive/MyDrive/archivos/data.xlsx')

#2-Mostrar los primeros 5 valores del dataframe#
data.head()

#3-Mostrar los últimos 5 valores del dataframe#
data.tail()

#4-Mostrar el tipo de dato (Dtype) de cada columna(Ejemplo si es Integer, object,
#float, etc)#
data.dtypes

#5-Mostrar la cantidad de valores nulos de cada columna#
data.isnull().sum()

#6-Mostrar el porcentaje total de valores perdidos en todo el dataframe#
cant_datos = np.product(data.shape)
na_ratio = ((data.isnull().sum().sum()/cant_datos)*100)
print(na_ratio)

#7-Mostrar el porcentaje de valores perdidos por columna#
na_col_ratio = ((data.isnull().sum() / len(data))*100).sort_values(ascending = False)
print(na_col_ratio)

#8-Eliminar aquella columna (s) que tengan más del 70% de sus valores en nulo#
data.drop('Taxes', axis=1, inplace=True)

#9- Eliminar aquellas filas que tenga menos de dos elementos#

#Filas vacias#
print(data.iloc[[182,592]])

data.drop([182,592], axis=0, inplace=True)

#10- Reemplace los String “--" por valores nulos#
data = data.replace({"--": np.nan})
data['Status']

#11- Reemplazar los valores nulos de la columna de “Gender” por U (Unknown) para
#aquellos empleados que no especificaron este campo#
data['Gender'].fillna("U", inplace=True)
data.isnull().sum()

#12- Reemplazar los valores nulos de la columna “Departamento” por “Bench”#
data['Department'].fillna("Bench", inplace=True)
data.isnull().sum()

#13- Reemplazar los valores nulos de la columna “HourlyRate” por la mediana#
data['HourlyRate'] = pd.to_numeric(data['HourlyRate'],errors = 'coerce')
mediana = data['HourlyRate'].median()
data['HourlyRate'].fillna(mediana, inplace=True)
data.isnull().sum()

#14- Reemplazar los valores perdidos inesperados de la columna “Overtime” por No#
cnt=0
for row in data['OverTime']:
    try:
        int(row)
        data.loc[cnt, 'OverTime']=np.nan
    except ValueError:
        pass
    cnt+=1
data.isnull().sum()
data['OverTime'].fillna('NO', inplace=True)
data.isnull().sum()

#15- Salvar el dataframe una vez realizado el procesamiento de los puntos
#anteriores
data.to_excel('/content/drive/MyDrive/archivos/cleanData.xlsx',header=True)